# Generated by Django 4.0.4 on 2022-09-23 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Usuário', max_length=100)),
                ('email', models.EmailField(default='email@email.com', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Título do post', max_length=60)),
                ('image', models.ImageField(default='default.jpeg', upload_to='posts_image/%m')),
                ('text', models.TextField(default='Área de texto', max_length=2000)),
                ('likes', models.IntegerField(default=0)),
                ('category', models.CharField(choices=[('TECH', 'Tecnologia'), ('MUND', 'Mundo'), ('SPRT', 'Esportes'), ('ECON', 'Economia'), ('PLTC', 'Política'), ('ETTN', 'Entretenimento'), ('SAUD', 'Saúde'), ('EDUC', 'Educação')], default='TECH', max_length=4)),
            ],
        ),
    ]
